# Generated by Django 2.2.7 on 2019-11-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(blank=True, max_length=22, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Gradeestudo',
            fields=[
                ('aluno', models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Projetos.Usuario')),
                ('materias', models.ForeignKey(db_column='materias', on_delete=django.db.models.deletion.DO_NOTHING, to='Projetos.Materia')),
            ],
            options={
                'db_table': 'gradeestudo',
                'unique_together': {('aluno', 'materias')},
            },
        ),
    ]
