# Generated by Django 2.2.7 on 2019-11-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(blank=True, max_length=255, null=True)),
                ('aluno', models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='Projetos.Usuario')),
                ('materia', models.ForeignKey(blank=True, db_column='materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Projetos.Materia')),
            ],
            options={
                'db_table': 'atividade',
            },
        ),
    ]
