# Generated by Django 2.2.7 on 2019-11-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0002_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeestudo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gradeestudo',
            name='aluno',
            field=models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='Projetos.Usuario'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='gradeestudo',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='atividade',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gradeestudo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='materia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
        migrations.CreateModel(
            name='Horarioestudo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(blank=True, max_length=3, null=True)),
                ('aluno', models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='Projetos.Usuario')),
                ('materias', models.ForeignKey(db_column='materias', on_delete=django.db.models.deletion.DO_NOTHING, to='Projetos.Materia')),
            ],
        ),
    ]
