# Generated by Django 2.2.7 on 2019-12-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0003_auto_20191128_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gradeestudo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='horarioestudo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
