# Generated by Django 2.2.7 on 2019-12-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0004_auto_20191201_1811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atividade',
            table='atividade',
        ),
        migrations.AlterModelTable(
            name='gradeestudo',
            table='gradeestudo',
        ),
        migrations.AlterModelTable(
            name='horarioestudo',
            table='horarioestudo',
        ),
        migrations.AlterModelTable(
            name='materia',
            table='materia',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
